print("Tarea 2: definiciones y conjutos.")
print("Tarea Realiazada por: Aldo Jaccopo Del Fierro Flores 20110175")
print("Que definicion gusta saber?")
print("1) 1.1.1. Definición formal de conjunto.")
print("2) 1.1.2. El conjunto universal y el conjunto vacío.")
print("3) 1.1.3. Definición de conjuntos por extensión y por comprensión.")
print("4) 1.2. Operaciones con conjuntos.")
print("5) 1.2.1. lgualdad de conjuntos.")
print("6) 1.2.2. Subconjunto y superconjunto.")
print("7) 1.2.3. Unión, Intersección, complemento, diferencia y diferencia simétrica.")
print("8) 1.3. Funciones.")
print("9) 1.3.1.Producto cartesiano.")
print("10) 1.3.2. Relaciones.")
print("11) SALIR.")